// Serves the service worker so its cache name carries a build-time version.
// A static public/sw.js had a hard-coded cache name ("p101-v1") that never
// changed, so the `activate` step never evicted the previous cache and users
// kept getting served stale precached HTML/assets after a deploy. Stamping the
// version at build time means every deploy creates a fresh cache and the old
// one is deleted on activate.

export const dynamic = "force-static";

// Stamped once at build time. NEXT_PUBLIC_BUILD_ID is set per deploy on most
// hosts; otherwise fall back to the build timestamp so each build differs.
const CACHE_VERSION = process.env.NEXT_PUBLIC_BUILD_ID ?? String(Date.now());

const SW_SOURCE = `// Growly — Service Worker (generated by app/sw.js/route.ts)
// Offline-first strategy: cache on install, serve from cache with network update.

const CACHE = "growly-${CACHE_VERSION}";
// Key app routes are precached so the app is usable offline immediately.
// The most frequently accessed pages take priority; less-visited routes are
// cached automatically on first visit via the network-first fetch handler.
const PRECACHE_URLS = [
  "/",
  "/dashboard",
  "/today",
  "/habits",
  "/tracker",
  "/offline",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))),
  );
  event.waitUntil(self.clients.claim());

  // After activation, prefetch secondary routes in the background so they
  // are available offline even before the user visits them for the first time.
  // This runs asynchronously and does not block the activation promise.
  const SECONDARY_ROUTES = [
    "/goals",
    "/notes",
    "/stats",
    "/calendar",
    "/friends",
    "/leaderboard",
    "/achievements",
    "/shop",
    "/settings",
    "/suggestions",
    "/templates",
    "/notifications",
    "/profile",
  ];
  caches.open(CACHE).then((cache) => {
    // Fetch each secondary route with a cache-first strategy — if the
    // fetch succeeds, the response is cached; if it fails, the route will
    // be cached on first visit via the normal fetch handler.
    for (const route of SECONDARY_ROUTES) {
      fetch(route)
        .then((res) => {
          if (res.ok) cache.put(route, res);
        })
        .catch(() => {
          // Silently ignore — the route will be cached on first visit
        });
    }
  }).catch(() => {});
});

// Build a minimal HTML fallback page for when the network is unavailable
// AND the offline page isn't cached yet (e.g. first install before precache
// completes, or after a cache eviction).
const FALLBACK_HTML = \`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offline</title><style>body{display:grid;place-items:center;min-height:100dvh;margin:0;background:#0f0f13;color:#e4e4e7;font-family:system-ui,sans-serif;text-align:center;padding:1rem}div{max-width:360px}h1{font-size:1.5rem;margin:0 0 .5rem}p{color:#a1a1aa;margin:0}</style></head><body><div><span style="font-size:3rem">🌱</span><h1>You&#39;re offline</h1><p>Please check your connection and try again.</p></div></body></html>\`;

const FALLBACK_RESPONSE = new Response(FALLBACK_HTML, {
  status: 200,
  statusText: "OK",
  headers: { "Content-Type": "text/html; charset=utf-8" },
});

// Network-first with cache fallback for HTML/navigation requests.
// Cache-first with stale-while-revalidate for static assets.
// Every catch() chain MUST return a valid Response to avoid
// "Failed to convert value to 'Response'" TypeError.
self.addEventListener("fetch", (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Only handle same-origin requests
  if (url.origin !== self.location.origin) return;

  // For navigation requests (HTML pages), try network first, fall back to cache
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const cloned = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, cloned)).catch(() => {});
          }
          return response;
        })
        .catch(() =>
          caches.match(request).then(
            (cached) => cached || caches.match("/offline"),
          ).then((cached) => cached || FALLBACK_RESPONSE),
        ),
    );
    return;
  }

  // For static assets (JS, CSS, images, fonts), cache-first
  if (
    request.destination === "script" ||
    request.destination === "style" ||
    request.destination === "image" ||
    request.destination === "font"
  ) {
    event.respondWith(
      caches.match(request).then((cached) => {
        const fetchPromise = fetch(request)
          .then((response) => {
            if (response.ok) {
              const cloned = response.clone();
              caches.open(CACHE).then((cache) => cache.put(request, cloned)).catch(() => {});
            }
            return response;
          })
          .catch(() => cached);
        return cached || fetchPromise;
      }).then((response) => response || FALLBACK_RESPONSE),
    );
    return;
  }

  // For API-like requests (/_next/...), network-first with cache fallback
  event.respondWith(
    fetch(request)
      .then((response) => {
        if (response.ok) {
          const cloned = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, cloned)).catch(() => {});
        }
        return response;
      })
      .catch(() =>
        caches.match(request).then((cached) => cached || new Response(
          JSON.stringify({ error: "offline" }),
          { status: 503, headers: { "Content-Type": "application/json" } },
        )),
      ),
  );
});
`;

export async function GET() {
  return new Response(SW_SOURCE, {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // Never let the browser serve a stale SW script; updates must be picked up
      // so a new cache version actually takes effect.
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
