// Serves the service worker so its cache name carries a build-time version.
// A static public/sw.js had a hard-coded cache name ("p101-v1") that never
// changed, so the `activate` step never evicted the previous cache and users
// kept getting served stale precached HTML/assets after a deploy. Stamping the
// version at build time means every deploy creates a fresh cache and the old
// one is deleted on activate.

export const dynamic = "force-static";

// Stamped once at build time. NEXT_PUBLIC_BUILD_ID is set per deploy on most
// hosts; otherwise fall back to the build timestamp so each build differs.
const CACHE_VERSION = process.env.NEXT_PUBLIC_BUILD_ID ?? String(Date.now());

const SW_SOURCE = `// Growly — Service Worker (generated by app/sw.js/route.ts)
// Offline-first strategy: cache on install, serve from cache with network update.

const CACHE = "growly-${CACHE_VERSION}";
const PRECACHE_URLS = ["/", "/offline"];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))),
  );
  event.waitUntil(self.clients.claim());
});

// Network-first with cache fallback for HTML/navigation requests.
// Cache-first with stale-while-revalidate for static assets.
self.addEventListener("fetch", (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Only handle same-origin requests
  if (url.origin !== self.location.origin) return;

  // For navigation requests (HTML pages), try network first, fall back to cache
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          if (response.ok) {
            const cloned = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, cloned)).catch(() => {});
          }
          return response;
        })
        .catch(() => caches.match(request).then((cached) => cached || caches.match("/offline"))),
    );
    return;
  }

  // For static assets (JS, CSS, images, fonts), cache-first
  if (
    request.destination === "script" ||
    request.destination === "style" ||
    request.destination === "image" ||
    request.destination === "font"
  ) {
    event.respondWith(
      caches.match(request).then((cached) => {
        const fetchPromise = fetch(request)
          .then((response) => {
            if (response.ok) {
              const cloned = response.clone();
              caches.open(CACHE).then((cache) => cache.put(request, cloned)).catch(() => {});
            }
            return response;
          })
          .catch(() => cached);
        return cached || fetchPromise;
      }),
    );
    return;
  }

  // For API-like requests (/_next/...), network-first with cache fallback
  event.respondWith(
    fetch(request)
      .then((response) => {
        if (response.ok) {
          const cloned = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, cloned)).catch(() => {});
        }
        return response;
      })
      .catch(() => caches.match(request)),
  );
});
`;

export async function GET() {
  return new Response(SW_SOURCE, {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // Never let the browser serve a stale SW script; updates must be picked up
      // so a new cache version actually takes effect.
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
